# binder environment stuff
name: dummy-binder

channels:
  - conda-forge

dependencies:
  - python=3.11
  - matplotlib
  - pandas
  - pip
  # jupysql-plugin doesn't work with jupyterlab 4
  - jupyterlab<4
  - pip:
    # duckdb example
    - duckdb
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    # required to open .md files as nbs
    - jupytext<1.15
    # jupysql
    - git+https://github.com/ploomber/jupysql
    - jupysql-plugin