# binder environment stuff
name: dummy-binder

channels:
  - conda-forge

dependencies:
  - python=3.11
  - matplotlib
  - pandas
  - pip
  - pip:
    # duckdb example
    - duckdb
    - duckdb-engine
    # plot example
    - memory-profiler
    - pyarrow
    # required to open .md files as nbs
    # - jupytext
    # jupysql
    # - git+https://github.com/ploomber/jupysql
