name: check-pr

on: [pull_request]

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PR
        run: |

          git fetch origin
          git pull $GITHUB_BASE_REF
          git --no-pager diff --name-only --diff-filter=ACMRT $GITHUB_BASE_REF
