name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8

      - name: Install dependencies
        run: |

          pip install .
          # check package is importable
          python -c "import ploomber_dummy"
          pip install ".[dev]"


      - name: Test with pytest
        run: |
          pytest --durations-min=5


  # run: pkgmt check
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pkgmt[check]'
      - name: Check project
        run: |
          pkgmt check

  release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && startsWith(github.event.head_commit.message, '[release]')
    needs: [test, check]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pkgmt[check]' twine wheel

      - name: Configure git
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"

      - name: Bump up tag version 
        run: |
          pkgmt version --yes

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          TAG=$(git describe --abbrev=0)
          echo yes | pkgmt release $TAG --production

  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create and merge PR
        env:
          BRANCH_NAME : ${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: "release-pr"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

          echo "Creating PR \"$PR_TITLE\" for branch $BRANCH_NAME"
          gh pr create --title "$PR_TITLE" --body "This is an automated PR to update blog posts"
          gh pr merge --auto --delete-branch --squash "$BRANCH_NAME"    